/*
	File generated by NetTiers templates [www.nettiers.net]
	Generated on : Thursday, May 12, 2016
	Important: Do not modify this file. Edit the file VwHoldAndCallWithLeadInfo.cs instead.
*/
#region Using Directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Runtime.Serialization;
using System.Xml.Serialization;
#endregion

namespace SalesWorkflow.Entities
{
	///<summary>
	/// An object representation of the 'vw_HoldAndCallWithLeadInfo' view. [No description found in the database]	
	///</summary>
	[Serializable]
	[CLSCompliant(true)]
	[ToolboxItem("VwHoldAndCallWithLeadInfoBase")]
	public abstract partial class VwHoldAndCallWithLeadInfoBase : System.IComparable, System.ICloneable, INotifyPropertyChanged
	{
		
		#region Variable Declarations
		
		/// <summary>
		/// First Name : 
		/// </summary>
		private System.String		  _firstName = null;
		
		/// <summary>
		/// Last Name : 
		/// </summary>
		private System.String		  _lastName = null;
		
		/// <summary>
		/// Lead Status : 
		/// </summary>
		private System.String		  _leadStatus = null;
		
		/// <summary>
		/// Rating : 
		/// </summary>
		private System.String		  _rating = null;
		
		/// <summary>
		/// Lead Owner : 
		/// </summary>
		private System.String		  _leadOwner = null;
		
		/// <summary>
		/// LeadHoldDts : 
		/// </summary>
		private System.DateTime		  _leadHoldDts = DateTime.MinValue;
		
		/// <summary>
		/// LeadCalled : 
		/// </summary>
		private System.Boolean?		  _leadCalled = null;
		
		/// <summary>
		/// LeadDefered : 
		/// </summary>
		private System.Boolean?		  _leadDefered = null;
		
		/// <summary>
		/// LeadActionDts : 
		/// </summary>
		private System.DateTime?		  _leadActionDts = null;
		
		/// <summary>
		/// LEADID : 
		/// </summary>
		private System.String		  _leadid = null;
		
		/// <summary>
		/// USER_ID : 
		/// </summary>
		private System.String		  _userId = string.Empty;
		
		/// <summary>
		/// Object that contains data to associate with this object
		/// </summary>
		private object _tag;
		
		/// <summary>
		/// Suppresses Entity Events from Firing, 
		/// useful when loading the entities from the database.
		/// </summary>
	    [NonSerialized] 
		private bool suppressEntityEvents = false;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="VwHoldAndCallWithLeadInfoBase"/> instance.
		///</summary>
		public VwHoldAndCallWithLeadInfoBase()
		{
		}		
		
		///<summary>
		/// Creates a new <see cref="VwHoldAndCallWithLeadInfoBase"/> instance.
		///</summary>
		///<param name="_firstName"></param>
		///<param name="_lastName"></param>
		///<param name="_leadStatus"></param>
		///<param name="_rating"></param>
		///<param name="_leadOwner"></param>
		///<param name="_leadHoldDts"></param>
		///<param name="_leadCalled"></param>
		///<param name="_leadDefered"></param>
		///<param name="_leadActionDts"></param>
		///<param name="_leadid"></param>
		///<param name="_userId"></param>
		public VwHoldAndCallWithLeadInfoBase(System.String _firstName, System.String _lastName, System.String _leadStatus, System.String _rating, System.String _leadOwner, System.DateTime _leadHoldDts, System.Boolean? _leadCalled, System.Boolean? _leadDefered, System.DateTime? _leadActionDts, System.String _leadid, System.String _userId)
		{
			this._firstName = _firstName;
			this._lastName = _lastName;
			this._leadStatus = _leadStatus;
			this._rating = _rating;
			this._leadOwner = _leadOwner;
			this._leadHoldDts = _leadHoldDts;
			this._leadCalled = _leadCalled;
			this._leadDefered = _leadDefered;
			this._leadActionDts = _leadActionDts;
			this._leadid = _leadid;
			this._userId = _userId;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="VwHoldAndCallWithLeadInfo"/> instance.
		///</summary>
		///<param name="_firstName"></param>
		///<param name="_lastName"></param>
		///<param name="_leadStatus"></param>
		///<param name="_rating"></param>
		///<param name="_leadOwner"></param>
		///<param name="_leadHoldDts"></param>
		///<param name="_leadCalled"></param>
		///<param name="_leadDefered"></param>
		///<param name="_leadActionDts"></param>
		///<param name="_leadid"></param>
		///<param name="_userId"></param>
		public static VwHoldAndCallWithLeadInfo CreateVwHoldAndCallWithLeadInfo(System.String _firstName, System.String _lastName, System.String _leadStatus, System.String _rating, System.String _leadOwner, System.DateTime _leadHoldDts, System.Boolean? _leadCalled, System.Boolean? _leadDefered, System.DateTime? _leadActionDts, System.String _leadid, System.String _userId)
		{
			VwHoldAndCallWithLeadInfo newVwHoldAndCallWithLeadInfo = new VwHoldAndCallWithLeadInfo();
			newVwHoldAndCallWithLeadInfo.FirstName = _firstName;
			newVwHoldAndCallWithLeadInfo.LastName = _lastName;
			newVwHoldAndCallWithLeadInfo.LeadStatus = _leadStatus;
			newVwHoldAndCallWithLeadInfo.Rating = _rating;
			newVwHoldAndCallWithLeadInfo.LeadOwner = _leadOwner;
			newVwHoldAndCallWithLeadInfo.LeadHoldDts = _leadHoldDts;
			newVwHoldAndCallWithLeadInfo.LeadCalled = _leadCalled;
			newVwHoldAndCallWithLeadInfo.LeadDefered = _leadDefered;
			newVwHoldAndCallWithLeadInfo.LeadActionDts = _leadActionDts;
			newVwHoldAndCallWithLeadInfo.Leadid = _leadid;
			newVwHoldAndCallWithLeadInfo.UserId = _userId;
			return newVwHoldAndCallWithLeadInfo;
		}
				
		#endregion Constructors
		
		#region Properties	
		/// <summary>
		/// 	Gets or Sets the First Name property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String FirstName
		{
			get
			{
				return this._firstName; 
			}
			set
			{
				if (_firstName == value)
					return;
					
				this._firstName = value;
				this._isDirty = true;
				
				OnPropertyChanged("FirstName");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the Last Name property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String LastName
		{
			get
			{
				return this._lastName; 
			}
			set
			{
				if (_lastName == value)
					return;
					
				this._lastName = value;
				this._isDirty = true;
				
				OnPropertyChanged("LastName");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the Lead Status property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String LeadStatus
		{
			get
			{
				return this._leadStatus; 
			}
			set
			{
				if (_leadStatus == value)
					return;
					
				this._leadStatus = value;
				this._isDirty = true;
				
				OnPropertyChanged("LeadStatus");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the Rating property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String Rating
		{
			get
			{
				return this._rating; 
			}
			set
			{
				if (_rating == value)
					return;
					
				this._rating = value;
				this._isDirty = true;
				
				OnPropertyChanged("Rating");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the Lead Owner property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String LeadOwner
		{
			get
			{
				return this._leadOwner; 
			}
			set
			{
				if (_leadOwner == value)
					return;
					
				this._leadOwner = value;
				this._isDirty = true;
				
				OnPropertyChanged("LeadOwner");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the LeadHoldDts property. 
		///		
		/// </summary>
		/// <value>This type is datetime</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.DateTime LeadHoldDts
		{
			get
			{
				return this._leadHoldDts; 
			}
			set
			{
				if (_leadHoldDts == value)
					return;
					
				this._leadHoldDts = value;
				this._isDirty = true;
				
				OnPropertyChanged("LeadHoldDts");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the LeadCalled property. 
		///		
		/// </summary>
		/// <value>This type is bit</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return false. It is up to the developer
		/// to check the value of IsLeadCalledNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Boolean? LeadCalled
		{
			get
			{
				return this._leadCalled; 
			}
			set
			{
				if (_leadCalled == value && LeadCalled != null )
					return;
					
				this._leadCalled = value;
				this._isDirty = true;
				
				OnPropertyChanged("LeadCalled");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the LeadDefered property. 
		///		
		/// </summary>
		/// <value>This type is bit</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return false. It is up to the developer
		/// to check the value of IsLeadDeferedNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.Boolean? LeadDefered
		{
			get
			{
				return this._leadDefered; 
			}
			set
			{
				if (_leadDefered == value && LeadDefered != null )
					return;
					
				this._leadDefered = value;
				this._isDirty = true;
				
				OnPropertyChanged("LeadDefered");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the LeadActionDts property. 
		///		
		/// </summary>
		/// <value>This type is datetime</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsLeadActionDtsNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.DateTime? LeadActionDts
		{
			get
			{
				return this._leadActionDts; 
			}
			set
			{
				if (_leadActionDts == value && LeadActionDts != null )
					return;
					
				this._leadActionDts = value;
				this._isDirty = true;
				
				OnPropertyChanged("LeadActionDts");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the LEADID property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String Leadid
		{
			get
			{
				return this._leadid; 
			}
			set
			{
				if (_leadid == value)
					return;
					
				this._leadid = value;
				this._isDirty = true;
				
				OnPropertyChanged("Leadid");
			}
		}
		
		/// <summary>
		/// 	Gets or Sets the USER_ID property. 
		///		
		/// </summary>
		/// <value>This type is varchar</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		public virtual System.String UserId
		{
			get
			{
				return this._userId; 
			}
			set
			{
				if ( value == null )
					throw new ArgumentNullException("value", "UserId does not allow null values.");
				if (_userId == value)
					return;
					
				this._userId = value;
				this._isDirty = true;
				
				OnPropertyChanged("UserId");
			}
		}
		
		
		/// <summary>
		///     Gets or sets the object that contains supplemental data about this object.
		/// </summary>
		/// <value>Object</value>
		[System.ComponentModel.Bindable(false)]
		[LocalizableAttribute(false)]
		[DescriptionAttribute("Object containing data to be associated with this object")]
		public virtual object Tag
		{
			get
			{
				return this._tag;
			}
			set
			{
				if (this._tag == value)
					return;
		
				this._tag = value;
			}
		}
	
		/// <summary>
		/// Determines whether this entity is to suppress events while set to true.
		/// </summary>
		[System.ComponentModel.Bindable(false)]
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public bool SuppressEntityEvents
		{	
			get
			{
				return suppressEntityEvents;
			}
			set
			{
				suppressEntityEvents = value;
			}	
		}

		private bool _isDeleted = false;
		/// <summary>
		/// Gets a value indicating if object has been <see cref="MarkToDelete"/>. ReadOnly.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsDeleted
		{
			get { return this._isDeleted; }
		}


		private bool _isDirty = false;
		/// <summary>
		///	Gets a value indicating  if the object has been modified from its original state.
		/// </summary>
		///<value>True if object has been modified from its original state; otherwise False;</value>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsDirty
		{
			get { return this._isDirty; }
		}
		

		private bool _isNew = true;
		/// <summary>
		///	Gets a value indicating if the object is new.
		/// </summary>
		///<value>True if objectis new; otherwise False;</value>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public virtual bool IsNew
		{
			get { return this._isNew; }
			set { this._isNew = value; }
		}

		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public string ViewName
		{
			get { return "vw_HoldAndCallWithLeadInfo"; }
		}

		
		#endregion
		
		#region Methods	
		
		/// <summary>
		/// Accepts the changes made to this object by setting each flags to false.
		/// </summary>
		public virtual void AcceptChanges()
		{
			this._isDeleted = false;
			this._isDirty = false;
			this._isNew = false;
			OnPropertyChanged(string.Empty);
		}
		
		
		///<summary>
		///  Revert all changes and restore original values.
		///  Currently not supported.
		///</summary>
		/// <exception cref="NotSupportedException">This method is not currently supported and always throws this exception.</exception>
		public virtual void CancelChanges()
		{
			throw new NotSupportedException("Method currently not Supported.");
		}
		
		///<summary>
		///   Marks entity to be deleted.
		///</summary>
		public virtual void MarkToDelete()
		{
			this._isDeleted = true;
		}
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed VwHoldAndCallWithLeadInfoBase Entity 
		///</summary>
		public virtual VwHoldAndCallWithLeadInfoBase Copy()
		{
			//shallow copy entity
			VwHoldAndCallWithLeadInfo copy = new VwHoldAndCallWithLeadInfo();
				copy.FirstName = this.FirstName;
				copy.LastName = this.LastName;
				copy.LeadStatus = this.LeadStatus;
				copy.Rating = this.Rating;
				copy.LeadOwner = this.LeadOwner;
				copy.LeadHoldDts = this.LeadHoldDts;
				copy.LeadCalled = this.LeadCalled;
				copy.LeadDefered = this.LeadDefered;
				copy.LeadActionDts = this.LeadActionDts;
				copy.Leadid = this.Leadid;
				copy.UserId = this.UserId;
			copy.AcceptChanges();
			return (VwHoldAndCallWithLeadInfo)copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Deep Copy of this entity.
		///</summary>
		public object Clone(){
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		#endregion
		
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="VwHoldAndCallWithLeadInfoBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(VwHoldAndCallWithLeadInfoBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="VwHoldAndCallWithLeadInfoBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="VwHoldAndCallWithLeadInfoBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="VwHoldAndCallWithLeadInfoBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(VwHoldAndCallWithLeadInfoBase Object1, VwHoldAndCallWithLeadInfoBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;

			bool equal = true;
			if (Object1.FirstName != null && Object2.FirstName != null )
			{
				if (Object1.FirstName != Object2.FirstName)
					equal = false;
			}
			else if (Object1.FirstName == null ^ Object1.FirstName == null )
			{
				equal = false;
			}
			if (Object1.LastName != null && Object2.LastName != null )
			{
				if (Object1.LastName != Object2.LastName)
					equal = false;
			}
			else if (Object1.LastName == null ^ Object1.LastName == null )
			{
				equal = false;
			}
			if (Object1.LeadStatus != null && Object2.LeadStatus != null )
			{
				if (Object1.LeadStatus != Object2.LeadStatus)
					equal = false;
			}
			else if (Object1.LeadStatus == null ^ Object1.LeadStatus == null )
			{
				equal = false;
			}
			if (Object1.Rating != null && Object2.Rating != null )
			{
				if (Object1.Rating != Object2.Rating)
					equal = false;
			}
			else if (Object1.Rating == null ^ Object1.Rating == null )
			{
				equal = false;
			}
			if (Object1.LeadOwner != null && Object2.LeadOwner != null )
			{
				if (Object1.LeadOwner != Object2.LeadOwner)
					equal = false;
			}
			else if (Object1.LeadOwner == null ^ Object1.LeadOwner == null )
			{
				equal = false;
			}
			if (Object1.LeadHoldDts != Object2.LeadHoldDts)
				equal = false;
			if (Object1.LeadCalled != null && Object2.LeadCalled != null )
			{
				if (Object1.LeadCalled != Object2.LeadCalled)
					equal = false;
			}
			else if (Object1.LeadCalled == null ^ Object1.LeadCalled == null )
			{
				equal = false;
			}
			if (Object1.LeadDefered != null && Object2.LeadDefered != null )
			{
				if (Object1.LeadDefered != Object2.LeadDefered)
					equal = false;
			}
			else if (Object1.LeadDefered == null ^ Object1.LeadDefered == null )
			{
				equal = false;
			}
			if (Object1.LeadActionDts != null && Object2.LeadActionDts != null )
			{
				if (Object1.LeadActionDts != Object2.LeadActionDts)
					equal = false;
			}
			else if (Object1.LeadActionDts == null ^ Object1.LeadActionDts == null )
			{
				equal = false;
			}
			if (Object1.Leadid != null && Object2.Leadid != null )
			{
				if (Object1.Leadid != Object2.Leadid)
					equal = false;
			}
			else if (Object1.Leadid == null ^ Object1.Leadid == null )
			{
				equal = false;
			}
			if (Object1.UserId != Object2.UserId)
				equal = false;
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
		}
	
		#endregion
		
		#region INotifyPropertyChanged Members
		
		/// <summary>
      /// Event to indicate that a property has changed.
      /// </summary>
		[field:NonSerialized]
		public event PropertyChangedEventHandler PropertyChanged;

		/// <summary>
      /// Called when a property is changed
      /// </summary>
      /// <param name="propertyName">The name of the property that has changed.</param>
		protected virtual void OnPropertyChanged(string propertyName)
		{ 
			OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
		}
		
		/// <summary>
      /// Called when a property is changed
      /// </summary>
      /// <param name="e">PropertyChangedEventArgs</param>
		protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
		{
			if (!SuppressEntityEvents)
			{
				if (null != PropertyChanged)
				{
					PropertyChanged(this, e);
				}
			}
		}
		
		#endregion
				
		/// <summary>
		/// Gets the property value by name.
		/// </summary>
		/// <param name="entity">The entity.</param>
		/// <param name="propertyName">Name of the property.</param>
		/// <returns></returns>
		public static object GetPropertyValueByName(VwHoldAndCallWithLeadInfo entity, string propertyName)
		{
			switch (propertyName)
			{
				case "FirstName":
					return entity.FirstName;
				case "LastName":
					return entity.LastName;
				case "LeadStatus":
					return entity.LeadStatus;
				case "Rating":
					return entity.Rating;
				case "LeadOwner":
					return entity.LeadOwner;
				case "LeadHoldDts":
					return entity.LeadHoldDts;
				case "LeadCalled":
					return entity.LeadCalled;
				case "LeadDefered":
					return entity.LeadDefered;
				case "LeadActionDts":
					return entity.LeadActionDts;
				case "Leadid":
					return entity.Leadid;
				case "UserId":
					return entity.UserId;
			}
			return null;
		}
				
		/// <summary>
		/// Gets the property value by name.
		/// </summary>
		/// <param name="propertyName">Name of the property.</param>
		/// <returns></returns>
		public object GetPropertyValueByName(string propertyName)
		{			
			return GetPropertyValueByName(this as VwHoldAndCallWithLeadInfo, propertyName);
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{12}{11}- FirstName: {0}{11}- LastName: {1}{11}- LeadStatus: {2}{11}- Rating: {3}{11}- LeadOwner: {4}{11}- LeadHoldDts: {5}{11}- LeadCalled: {6}{11}- LeadDefered: {7}{11}- LeadActionDts: {8}{11}- Leadid: {9}{11}- UserId: {10}{11}", 
				(this.FirstName == null) ? string.Empty : this.FirstName.ToString(),
			     
				(this.LastName == null) ? string.Empty : this.LastName.ToString(),
			     
				(this.LeadStatus == null) ? string.Empty : this.LeadStatus.ToString(),
			     
				(this.Rating == null) ? string.Empty : this.Rating.ToString(),
			     
				(this.LeadOwner == null) ? string.Empty : this.LeadOwner.ToString(),
			     
				this.LeadHoldDts,
				(this.LeadCalled == null) ? string.Empty : this.LeadCalled.ToString(),
			     
				(this.LeadDefered == null) ? string.Empty : this.LeadDefered.ToString(),
			     
				(this.LeadActionDts == null) ? string.Empty : this.LeadActionDts.ToString(),
			     
				(this.Leadid == null) ? string.Empty : this.Leadid.ToString(),
			     
				this.UserId,
				System.Environment.NewLine, 
				this.GetType());
		}
	
	}//End Class
	
	
	/// <summary>
	/// Enumerate the VwHoldAndCallWithLeadInfo columns.
	/// </summary>
	[Serializable]
	public enum VwHoldAndCallWithLeadInfoColumn
	{
		/// <summary>
		/// First Name : 
		/// </summary>
		[EnumTextValue("First Name")]
		[ColumnEnum("First Name", typeof(System.String), System.Data.DbType.String, false, false, true, 255)]
		FirstName,
		/// <summary>
		/// Last Name : 
		/// </summary>
		[EnumTextValue("Last Name")]
		[ColumnEnum("Last Name", typeof(System.String), System.Data.DbType.String, false, false, true, 255)]
		LastName,
		/// <summary>
		/// Lead Status : 
		/// </summary>
		[EnumTextValue("Lead Status")]
		[ColumnEnum("Lead Status", typeof(System.String), System.Data.DbType.String, false, false, true, 255)]
		LeadStatus,
		/// <summary>
		/// Rating : 
		/// </summary>
		[EnumTextValue("Rating")]
		[ColumnEnum("Rating", typeof(System.String), System.Data.DbType.String, false, false, true, 255)]
		Rating,
		/// <summary>
		/// Lead Owner : 
		/// </summary>
		[EnumTextValue("Lead Owner")]
		[ColumnEnum("Lead Owner", typeof(System.String), System.Data.DbType.String, false, false, true, 255)]
		LeadOwner,
		/// <summary>
		/// LeadHoldDts : 
		/// </summary>
		[EnumTextValue("LeadHoldDts")]
		[ColumnEnum("LeadHoldDts", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		LeadHoldDts,
		/// <summary>
		/// LeadCalled : 
		/// </summary>
		[EnumTextValue("LeadCalled")]
		[ColumnEnum("LeadCalled", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
		LeadCalled,
		/// <summary>
		/// LeadDefered : 
		/// </summary>
		[EnumTextValue("LeadDefered")]
		[ColumnEnum("LeadDefered", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
		LeadDefered,
		/// <summary>
		/// LeadActionDts : 
		/// </summary>
		[EnumTextValue("LeadActionDts")]
		[ColumnEnum("LeadActionDts", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		LeadActionDts,
		/// <summary>
		/// LEADID : 
		/// </summary>
		[EnumTextValue("LEADID")]
		[ColumnEnum("LEADID", typeof(System.String), System.Data.DbType.String, false, false, true, 255)]
		Leadid,
		/// <summary>
		/// USER_ID : 
		/// </summary>
		[EnumTextValue("USER_ID")]
		[ColumnEnum("USER_ID", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 50)]
		UserId
	}//End enum

} // end namespace
