
/*
	File generated by NetTiers templates [www.nettiers.net]
	Generated on : Thursday, May 12, 2016
	Important: Do not modify this file. Edit the file VwAllLeadsWithCallsAndPeriods.cs instead.
*/

#region Using Directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Security.Permissions;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Security;
using System.Data;

using SalesWorkflow.Entities;
using SalesWorkflow.Entities.Validation;
using Entities = SalesWorkflow.Entities;
using SalesWorkflow.Data;
using SalesWorkflow.Data.Bases;


using Microsoft.Practices.EnterpriseLibrary.Logging;

#endregion 

namespace SalesWorkflow
{		
	
	///<summary>
	/// An object representation of the 'vw_AllLeadsWithCallsAndPeriods' View.
	///</summary>
	/// <remarks>
	/// IMPORTANT!!! You should not modify this partial  class, modify the VwAllLeadsWithCallsAndPeriods.cs file instead.
	/// All custom implementations should be done in the <see cref="VwAllLeadsWithCallsAndPeriods"/> class.
	/// </remarks>
	[DataObject]
	public partial class VwAllLeadsWithCallsAndPeriodsServiceBase : ServiceViewBase<VwAllLeadsWithCallsAndPeriods>
	{

		#region Constructors
		///<summary>
		/// Creates a new <see cref="VwAllLeadsWithCallsAndPeriods"/> instance .
		///</summary>
		public VwAllLeadsWithCallsAndPeriodsServiceBase() : base()
		{
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="VwAllLeadsWithCallsAndPeriods"/> instance.
		///</summary>
		///<param name="_leadStatus"></param>
		///<param name="_leadid"></param>
		///<param name="_createdTime"></param>
		///<param name="_firstName"></param>
		///<param name="_lastName"></param>
		///<param name="_ifNoLongerInterested"></param>
		///<param name="_lastActivityTime"></param>
		///<param name="_leadOwner"></param>
		///<param name="_rating"></param>
		///<param name="_state"></param>
		///<param name="_timeZone"></param>
		///<param name="_satMc"></param>
		///<param name="_satDc"></param>
		///<param name="_satAc"></param>
		///<param name="_satEc"></param>
		///<param name="_sunMc"></param>
		///<param name="_sunDc"></param>
		///<param name="_sunAc"></param>
		///<param name="_sunEc"></param>
		///<param name="_dmc"></param>
		///<param name="_ddc"></param>
		///<param name="_dac"></param>
		///<param name="_dec"></param>
		///<param name="_phone"></param>
		public static VwAllLeadsWithCallsAndPeriods CreateVwAllLeadsWithCallsAndPeriods(System.String _leadStatus, System.String _leadid, System.DateTime? _createdTime, System.String _firstName, System.String _lastName, System.String _ifNoLongerInterested, System.DateTime? _lastActivityTime, System.String _leadOwner, System.String _rating, System.String _state, System.String _timeZone, System.Int32? _satMc, System.Int32? _satDc, System.Int32? _satAc, System.Int32? _satEc, System.Int32? _sunMc, System.Int32? _sunDc, System.Int32? _sunAc, System.Int32? _sunEc, System.Int32? _dmc, System.Int32? _ddc, System.Int32? _dac, System.Int32? _dec, System.String _phone)
		{
			VwAllLeadsWithCallsAndPeriods newEntityVwAllLeadsWithCallsAndPeriods = new VwAllLeadsWithCallsAndPeriods();
			newEntityVwAllLeadsWithCallsAndPeriods.LeadStatus  = _leadStatus;
			newEntityVwAllLeadsWithCallsAndPeriods.Leadid  = _leadid;
			newEntityVwAllLeadsWithCallsAndPeriods.CreatedTime  = _createdTime;
			newEntityVwAllLeadsWithCallsAndPeriods.FirstName  = _firstName;
			newEntityVwAllLeadsWithCallsAndPeriods.LastName  = _lastName;
			newEntityVwAllLeadsWithCallsAndPeriods.IfNoLongerInterested  = _ifNoLongerInterested;
			newEntityVwAllLeadsWithCallsAndPeriods.LastActivityTime  = _lastActivityTime;
			newEntityVwAllLeadsWithCallsAndPeriods.LeadOwner  = _leadOwner;
			newEntityVwAllLeadsWithCallsAndPeriods.Rating  = _rating;
			newEntityVwAllLeadsWithCallsAndPeriods.State  = _state;
			newEntityVwAllLeadsWithCallsAndPeriods.TimeZone  = _timeZone;
			newEntityVwAllLeadsWithCallsAndPeriods.SatMc  = _satMc;
			newEntityVwAllLeadsWithCallsAndPeriods.SatDc  = _satDc;
			newEntityVwAllLeadsWithCallsAndPeriods.SatAc  = _satAc;
			newEntityVwAllLeadsWithCallsAndPeriods.SatEc  = _satEc;
			newEntityVwAllLeadsWithCallsAndPeriods.SunMc  = _sunMc;
			newEntityVwAllLeadsWithCallsAndPeriods.SunDc  = _sunDc;
			newEntityVwAllLeadsWithCallsAndPeriods.SunAc  = _sunAc;
			newEntityVwAllLeadsWithCallsAndPeriods.SunEc  = _sunEc;
			newEntityVwAllLeadsWithCallsAndPeriods.Dmc  = _dmc;
			newEntityVwAllLeadsWithCallsAndPeriods.Ddc  = _ddc;
			newEntityVwAllLeadsWithCallsAndPeriods.Dac  = _dac;
			newEntityVwAllLeadsWithCallsAndPeriods.Dec  = _dec;
			newEntityVwAllLeadsWithCallsAndPeriods.Phone  = _phone;
			return newEntityVwAllLeadsWithCallsAndPeriods;
		}
		#endregion Constructors

		#region Fields
		//private static SecurityContext<VwAllLeadsWithCallsAndPeriods> securityContext = new SecurityContext<VwAllLeadsWithCallsAndPeriods>();
		private static readonly string layerExceptionPolicy = "ServiceLayerExceptionPolicy";
		private static readonly bool noTranByDefault = false;
		private static readonly int defaultMaxRecords = 10000;
		#endregion 
		
		#region Data Access Methods
			
		#region Get 
		/// <summary>
		/// Attempts to do a parameterized version of a simple whereclause. 
		/// Returns rows meeting the whereClause condition from the DataSource.
		/// </summary>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
        /// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC);</param>
		/// <remarks>Does NOT Support Advanced Operations such as SubSelects.  See GetPaged for that functionality.</remarks>
		/// <returns>Returns a typed collection of Entity objects.</returns>
		public override VList<VwAllLeadsWithCallsAndPeriods> Get(string whereClause, string orderBy)
		{
			int totalCount = -1;
			return Get(whereClause, orderBy, 0, defaultMaxRecords, out totalCount);
		}

		/// <summary>
		/// Returns rows meeting the whereClause condition from the DataSource.
		/// </summary>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
        /// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC);</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="totalCount">out parameter to get total records for query</param>
		/// <remarks>Does NOT Support Advanced Operations such as SubSelects.  See GetPaged for that functionality.</remarks>
		/// <returns>Returns a typed collection TList{VwAllLeadsWithCallsAndPeriods} of <c>VwAllLeadsWithCallsAndPeriods</c> objects.</returns>
		public override VList<VwAllLeadsWithCallsAndPeriods> Get(string whereClause, string orderBy, int start, int pageLength, out int totalCount)
		{
			// throws security exception if not authorized
			//SecurityContext.IsAuthorized("Get");
								
			// get this data
			VList<VwAllLeadsWithCallsAndPeriods> list = null;
			totalCount = -1;
			TransactionManager transactionManager = null; 

			try
            {	
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction(noTranByDefault);
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
					
				//Access repository
				list = dataProvider.VwAllLeadsWithCallsAndPeriodsProvider.Get(transactionManager, whereClause, orderBy, start, pageLength, out totalCount);
				
				//if borrowed tran, leave open for next call
			}
            catch (Exception exc)
            {
				//if open, rollback, it's possible this is part of a larger commit
                if (transactionManager != null && transactionManager.IsOpen) 
					transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
			}
			return list;
		}
		
		#endregion Get Methods
		
		#region GetAll
		/// <summary>
		/// Get a complete collection of <see cref="VwAllLeadsWithCallsAndPeriods" /> entities.
		/// </summary>
		/// <returns></returns>
		public virtual VList<VwAllLeadsWithCallsAndPeriods> GetAll() 
		{
			int totalCount = -1;
			return GetAll(0, defaultMaxRecords, out totalCount);
		}

       
		/// <summary>
		/// Get a set portion of a complete list of <see cref="VwAllLeadsWithCallsAndPeriods" /> entities
		/// </summary>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="totalCount">out parameter, number of total rows in given query.</param>
		/// <returns>a <see cref="TList{VwAllLeadsWithCallsAndPeriods}"/> </returns>
		public override VList<VwAllLeadsWithCallsAndPeriods> GetAll(int start, int pageLength, out int totalCount) 
		{
			// throws security exception if not authorized
			//SecurityContext.IsAuthorized("GetAll");
			
			// get this data
			VList<VwAllLeadsWithCallsAndPeriods> list = null;
			totalCount = -1;
			TransactionManager transactionManager = null; 

			try
            {	
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction(noTranByDefault);
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;					

				//Access repository
				list = dataProvider.VwAllLeadsWithCallsAndPeriodsProvider.GetAll(transactionManager, start, pageLength, out totalCount);	
			}
            catch (Exception exc)
            {
				//if open, rollback, it's possible this is part of a larger commit
                if (transactionManager != null && transactionManager.IsOpen) 
					transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
			}
			return list;
		}
		#endregion GetAll

		#region GetPaged
		/// <summary>
		/// Gets a page of <see cref="TList{VwAllLeadsWithCallsAndPeriods}" /> rows from the DataSource.
		/// </summary>
		/// <param name="totalCount">Out Parameter, Number of rows in the DataSource.</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of <c>VwAllLeadsWithCallsAndPeriods</c> objects.</returns>
		public virtual VList<VwAllLeadsWithCallsAndPeriods> GetPaged(out int totalCount)
		{
			return GetPaged(null, null, 0, defaultMaxRecords, out totalCount);
		}
		
		/// <summary>
		/// Gets a page of <see cref="TList{VwAllLeadsWithCallsAndPeriods}" /> rows from the DataSource.
		/// </summary>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="totalCount">Number of rows in the DataSource.</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of <c>VwAllLeadsWithCallsAndPeriods</c> objects.</returns>
		public virtual VList<VwAllLeadsWithCallsAndPeriods> GetPaged(int start, int pageLength, out int totalCount)
		{
			return GetPaged(null, null, start, pageLength, out totalCount);
		}

		/// <summary>
		/// Gets a page of entity rows with a <see cref="TList{VwAllLeadsWithCallsAndPeriods}" /> from the DataSource with a where clause and order by clause.
		/// </summary>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC).</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="totalCount">Out Parameter, Number of rows in the DataSource.</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of <c>VwAllLeadsWithCallsAndPeriods</c> objects.</returns>
		public override VList<VwAllLeadsWithCallsAndPeriods> GetPaged(string whereClause,string orderBy, int start, int pageLength, out int totalCount)
		{
			// throws security exception if not authorized
			//SecurityContext.IsAuthorized("GetPaged");
			
			// get this data
			VList<VwAllLeadsWithCallsAndPeriods> list = null;
			totalCount = -1;
			TransactionManager transactionManager = null; 

			try
            {	
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction(noTranByDefault);
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
					
				//Access repository
				list = dataProvider.VwAllLeadsWithCallsAndPeriodsProvider.GetPaged(transactionManager, whereClause, orderBy, start, pageLength, out totalCount);
				
				//if borrowed tran, leave open for next call
			}
            catch (Exception exc)
            {
				//if open, rollback, it's possible this is part of a larger commit
                if (transactionManager != null && transactionManager.IsOpen) 
					transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
			}
			return list;			
		}
		
		/// <summary>
		/// Gets the number of rows in the DataSource that match the specified whereClause.
		/// This method is only provided as a workaround for the ObjectDataSource's need to 
		/// execute another method to discover the total count instead of using another param, like our out param.  
		/// This method should be avoided if using the ObjectDataSource or another method.
		/// </summary>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <param name="totalCount">Number of rows in the DataSource.</param>
		/// <returns>Returns the number of rows.</returns>
		public int GetTotalItems(string whereClause, out int totalCount)
		{
			GetPaged(whereClause, null, 0, defaultMaxRecords, out totalCount);
			return totalCount;
		}
		#endregion GetPaged	

		#region Find Methods

		/// <summary>
		/// 	Returns rows from the DataSource that meet the parameter conditions.
		/// </summary>
		/// <param name="parameters">A collection of <see cref="SqlFilterParameter"/> objects.</param>
		/// <returns>Returns a typed collection of <c>VwAllLeadsWithCallsAndPeriods</c> objects.</returns>
		public virtual VList<VwAllLeadsWithCallsAndPeriods> Find(IFilterParameterCollection parameters)
		{
			return Find(parameters, null);
		}
		
		/// <summary>
		/// 	Returns rows from the DataSource that meet the parameter conditions.
		/// </summary>
		/// <param name="parameters">A collection of <see cref="SqlFilterParameter"/> objects.</param>
		/// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC);</param>
		/// <returns>Returns a typed collection of <c>VwAllLeadsWithCallsAndPeriods</c> objects.</returns>
		public virtual VList<VwAllLeadsWithCallsAndPeriods> Find(IFilterParameterCollection parameters, string orderBy)
		{
			int count = 0;
			return Find(parameters, orderBy, 0, defaultMaxRecords, out count);
		}
		
		/// <summary>
		/// 	Returns rows from the DataSource that meet the parameter conditions.
		/// </summary>
		/// <param name="parameters">A collection of <see cref="SqlFilterParameter"/> objects.</param>
		/// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC);</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out. The number of rows that match this query.</param>
		/// <returns>Returns a typed collection of <c>VwAllLeadsWithCallsAndPeriods</c> objects.</returns>
		public override VList<VwAllLeadsWithCallsAndPeriods> Find(IFilterParameterCollection parameters, string orderBy, int start, int pageLength, out int count)
		{
			// throws security exception if not authorized
			//SecurityContext.IsAuthorized("Find");
								
			// get this data
			TransactionManager transactionManager = null; 
			VList<VwAllLeadsWithCallsAndPeriods> list = null;
			count = -1;
			
			try
            {	
				//since this is a read operation, don't create a tran by default, only use tran if provided to us for custom isolation level
				transactionManager = ConnectionScope.ValidateOrCreateTransaction(noTranByDefault);
				NetTiersProvider dataProvider = ConnectionScope.Current.DataProvider;
					
				//Access repository
				list = dataProvider.VwAllLeadsWithCallsAndPeriodsProvider.Find(transactionManager, parameters, orderBy, start, pageLength, out count);
			}
            catch (Exception exc)
            {
				//if open, rollback, it's possible this is part of a larger commit
                if (transactionManager != null && transactionManager.IsOpen) 
					transactionManager.Rollback();
				
				//Handle exception based on policy
                if (DomainUtil.HandleException(exc, layerExceptionPolicy)) 
					throw;
			}
			
			return list;
		}
		
		#endregion Find Methods
		
		#region Custom Methods
		#endregion
		
		#endregion Data Access Methods
		
	
	}//End Class
} // end namespace



