
/*
	File generated by NetTiers templates [www.nettiers.net]
	Generated on : Thursday, May 12, 2016
	Important: Do not modify this file. Edit the file LeadContacted.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using SalesWorkflow.Entities.Validation;
#endregion

namespace SalesWorkflow.Entities
{
	///<summary>
	/// An object representation of the 'LeadContacted' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class LeadContactedBase : EntityBase, ILeadContacted, IEntityId<LeadContactedKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private LeadContactedEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private LeadContactedEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private LeadContactedEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<LeadContacted> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event LeadContactedEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event LeadContactedEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="LeadContactedBase"/> instance.
		///</summary>
		public LeadContactedBase()
		{
			this.entityData = new LeadContactedEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="LeadContactedBase"/> instance.
		///</summary>
		///<param name="_leadid"></param>
		///<param name="_userId"></param>
		///<param name="_leadContactPhone"></param>
		///<param name="_leadContactEmail"></param>
		///<param name="_leadContactDts"></param>
		///<param name="_thisEventDts"></param>
		public LeadContactedBase(System.String _leadid, System.String _userId, System.Boolean? _leadContactPhone, 
			System.Boolean? _leadContactEmail, System.String _leadContactDts, System.DateTime? _thisEventDts)
		{
			this.entityData = new LeadContactedEntityData();
			this.backupData = null;

			this.Leadid = _leadid;
			this.UserId = _userId;
			this.LeadContactPhone = _leadContactPhone;
			this.LeadContactEmail = _leadContactEmail;
			this.LeadContactDts = _leadContactDts;
			this.ThisEventDts = _thisEventDts;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="LeadContacted"/> instance.
		///</summary>
		///<param name="_leadid"></param>
		///<param name="_userId"></param>
		///<param name="_leadContactPhone"></param>
		///<param name="_leadContactEmail"></param>
		///<param name="_leadContactDts"></param>
		///<param name="_thisEventDts"></param>
		public static LeadContacted CreateLeadContacted(System.String _leadid, System.String _userId, System.Boolean? _leadContactPhone, 
			System.Boolean? _leadContactEmail, System.String _leadContactDts, System.DateTime? _thisEventDts)
		{
			LeadContacted newLeadContacted = new LeadContacted();
			newLeadContacted.Leadid = _leadid;
			newLeadContacted.UserId = _userId;
			newLeadContacted.LeadContactPhone = _leadContactPhone;
			newLeadContacted.LeadContactEmail = _leadContactEmail;
			newLeadContacted.LeadContactDts = _leadContactDts;
			newLeadContacted.ThisEventDts = _thisEventDts;
			return newLeadContacted;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Leadid property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 50)]
		public virtual System.String Leadid
		{
			get
			{
				return this.entityData.Leadid; 
			}
			
			set
			{
				if (this.entityData.Leadid == value)
					return;
				
                OnPropertyChanging("Leadid");                    
				OnColumnChanging(LeadContactedColumn.Leadid, this.entityData.Leadid);
				this.entityData.Leadid = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LeadContactedColumn.Leadid, this.entityData.Leadid);
				OnPropertyChanged("Leadid");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the UserId property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 50)]
		public virtual System.String UserId
		{
			get
			{
				return this.entityData.UserId; 
			}
			
			set
			{
				if (this.entityData.UserId == value)
					return;
				
                OnPropertyChanging("UserId");                    
				OnColumnChanging(LeadContactedColumn.UserId, this.entityData.UserId);
				this.entityData.UserId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LeadContactedColumn.UserId, this.entityData.UserId);
				OnPropertyChanged("UserId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the LeadContactPhone property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Boolean? LeadContactPhone
		{
			get
			{
				return this.entityData.LeadContactPhone; 
			}
			
			set
			{
				if (this.entityData.LeadContactPhone == value)
					return;
				
                OnPropertyChanging("LeadContactPhone");                    
				OnColumnChanging(LeadContactedColumn.LeadContactPhone, this.entityData.LeadContactPhone);
				this.entityData.LeadContactPhone = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LeadContactedColumn.LeadContactPhone, this.entityData.LeadContactPhone);
				OnPropertyChanged("LeadContactPhone");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the LeadContactEmail property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Boolean? LeadContactEmail
		{
			get
			{
				return this.entityData.LeadContactEmail; 
			}
			
			set
			{
				if (this.entityData.LeadContactEmail == value)
					return;
				
                OnPropertyChanging("LeadContactEmail");                    
				OnColumnChanging(LeadContactedColumn.LeadContactEmail, this.entityData.LeadContactEmail);
				this.entityData.LeadContactEmail = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LeadContactedColumn.LeadContactEmail, this.entityData.LeadContactEmail);
				OnPropertyChanged("LeadContactEmail");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the LeadContactDts property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String LeadContactDts
		{
			get
			{
				return this.entityData.LeadContactDts; 
			}
			
			set
			{
				if (this.entityData.LeadContactDts == value)
					return;
				
                OnPropertyChanging("LeadContactDts");                    
				OnColumnChanging(LeadContactedColumn.LeadContactDts, this.entityData.LeadContactDts);
				this.entityData.LeadContactDts = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LeadContactedColumn.LeadContactDts, this.entityData.LeadContactDts);
				OnPropertyChanged("LeadContactDts");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the LeadContactedPk property. 
		///		
		/// </summary>
		/// <value>This type is bigint.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int64 LeadContactedPk
		{
			get
			{
				return this.entityData.LeadContactedPk; 
			}
			
			set
			{
				if (this.entityData.LeadContactedPk == value)
					return;
				
                OnPropertyChanging("LeadContactedPk");                    
				OnColumnChanging(LeadContactedColumn.LeadContactedPk, this.entityData.LeadContactedPk);
				this.entityData.LeadContactedPk = value;
				this.EntityId.LeadContactedPk = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LeadContactedColumn.LeadContactedPk, this.entityData.LeadContactedPk);
				OnPropertyChanged("LeadContactedPk");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ThisEventDts property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? ThisEventDts
		{
			get
			{
				return this.entityData.ThisEventDts; 
			}
			
			set
			{
				if (this.entityData.ThisEventDts == value)
					return;
				
                OnPropertyChanging("ThisEventDts");                    
				OnColumnChanging(LeadContactedColumn.ThisEventDts, this.entityData.ThisEventDts);
				this.entityData.ThisEventDts = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(LeadContactedColumn.ThisEventDts, this.entityData.ThisEventDts);
				OnPropertyChanged("ThisEventDts");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Leadid", "Leadid"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Leadid", "Leadid", 50));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("UserId", "User Id"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("UserId", "User Id", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("LeadContactDts", "Lead Contact Dts", 50));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "LeadContacted"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"LEADID", "USER_ID", "LeadContactPhone", "LeadContactEmail", "LeadContactDts", "LeadContactedPK", "ThisEventDts"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as LeadContactedEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (LeadContacted) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<LeadContacted>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as LeadContacted);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed LeadContacted Entity 
		///</summary>
		protected virtual LeadContacted Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			LeadContacted copy = new LeadContacted();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Leadid = this.Leadid;
				copy.UserId = this.UserId;
				copy.LeadContactPhone = this.LeadContactPhone;
				copy.LeadContactEmail = this.LeadContactEmail;
				copy.LeadContactDts = this.LeadContactDts;
				copy.LeadContactedPk = this.LeadContactedPk;
				copy.ThisEventDts = this.ThisEventDts;
			
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed LeadContacted Entity 
		///</summary>
		public virtual LeadContacted Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed LeadContacted Entity which is a deep copy of the current entity.
		///</summary>
		public virtual LeadContacted DeepCopy()
		{
			return EntityHelper.Clone<LeadContacted>(this as LeadContacted);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as LeadContactedEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new LeadContactedEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as LeadContactedEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(LeadContactedColumn column)
		{
			switch(column)
			{
					case LeadContactedColumn.Leadid:
					return entityData.Leadid != _originalData.Leadid;
					case LeadContactedColumn.UserId:
					return entityData.UserId != _originalData.UserId;
					case LeadContactedColumn.LeadContactPhone:
					return entityData.LeadContactPhone != _originalData.LeadContactPhone;
					case LeadContactedColumn.LeadContactEmail:
					return entityData.LeadContactEmail != _originalData.LeadContactEmail;
					case LeadContactedColumn.LeadContactDts:
					return entityData.LeadContactDts != _originalData.LeadContactDts;
					case LeadContactedColumn.LeadContactedPk:
					return entityData.LeadContactedPk != _originalData.LeadContactedPk;
					case LeadContactedColumn.ThisEventDts:
					return entityData.ThisEventDts != _originalData.ThisEventDts;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< LeadContactedColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Leadid != _originalData.Leadid;
			result = result || entityData.UserId != _originalData.UserId;
			result = result || entityData.LeadContactPhone != _originalData.LeadContactPhone;
			result = result || entityData.LeadContactEmail != _originalData.LeadContactEmail;
			result = result || entityData.LeadContactDts != _originalData.LeadContactDts;
			result = result || entityData.LeadContactedPk != _originalData.LeadContactedPk;
			result = result || entityData.ThisEventDts != _originalData.ThisEventDts;
			return result;
		}	
		
		///<summary>
		///  Returns a LeadContacted Entity with the original data.
		///</summary>
		public LeadContacted GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateLeadContacted(
				_originalData.Leadid,
				_originalData.UserId,
				_originalData.LeadContactPhone,
				_originalData.LeadContactEmail,
				_originalData.LeadContactDts,
				_originalData.ThisEventDts
				);
				
			return (LeadContacted)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="LeadContactedBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is LeadContactedBase)
				return ValueEquals(this, (LeadContactedBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="LeadContactedBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Leadid.GetHashCode() ^ 
					this.UserId.GetHashCode() ^ 
					((this.LeadContactPhone == null) ? string.Empty : this.LeadContactPhone.ToString()).GetHashCode() ^ 
					((this.LeadContactEmail == null) ? string.Empty : this.LeadContactEmail.ToString()).GetHashCode() ^ 
					((this.LeadContactDts == null) ? string.Empty : this.LeadContactDts.ToString()).GetHashCode() ^ 
					this.LeadContactedPk.GetHashCode() ^ 
					((this.ThisEventDts == null) ? string.Empty : this.ThisEventDts.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="LeadContactedBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(LeadContactedBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="LeadContactedBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="LeadContactedBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="LeadContactedBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(LeadContactedBase Object1, LeadContactedBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Leadid != Object2.Leadid)
				equal = false;
			if (Object1.UserId != Object2.UserId)
				equal = false;
			if ( Object1.LeadContactPhone != null && Object2.LeadContactPhone != null )
			{
				if (Object1.LeadContactPhone != Object2.LeadContactPhone)
					equal = false;
			}
			else if (Object1.LeadContactPhone == null ^ Object2.LeadContactPhone == null )
			{
				equal = false;
			}
			if ( Object1.LeadContactEmail != null && Object2.LeadContactEmail != null )
			{
				if (Object1.LeadContactEmail != Object2.LeadContactEmail)
					equal = false;
			}
			else if (Object1.LeadContactEmail == null ^ Object2.LeadContactEmail == null )
			{
				equal = false;
			}
			if ( Object1.LeadContactDts != null && Object2.LeadContactDts != null )
			{
				if (Object1.LeadContactDts != Object2.LeadContactDts)
					equal = false;
			}
			else if (Object1.LeadContactDts == null ^ Object2.LeadContactDts == null )
			{
				equal = false;
			}
			if (Object1.LeadContactedPk != Object2.LeadContactedPk)
				equal = false;
			if ( Object1.ThisEventDts != null && Object2.ThisEventDts != null )
			{
				if (Object1.ThisEventDts != Object2.ThisEventDts)
					equal = false;
			}
			else if (Object1.ThisEventDts == null ^ Object2.ThisEventDts == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((LeadContactedBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static LeadContactedComparer GetComparer()
        {
            return new LeadContactedComparer();
        }
        */

        // Comparer delegates back to LeadContacted
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(LeadContacted rhs, LeadContactedColumn which)
        {
            switch (which)
            {
            	
            	
            	case LeadContactedColumn.Leadid:
            		return this.Leadid.CompareTo(rhs.Leadid);
            		
            		                 
            	
            	
            	case LeadContactedColumn.UserId:
            		return this.UserId.CompareTo(rhs.UserId);
            		
            		                 
            	
            	
            	case LeadContactedColumn.LeadContactPhone:
            		return this.LeadContactPhone.Value.CompareTo(rhs.LeadContactPhone.Value);
            		
            		                 
            	
            	
            	case LeadContactedColumn.LeadContactEmail:
            		return this.LeadContactEmail.Value.CompareTo(rhs.LeadContactEmail.Value);
            		
            		                 
            	
            	
            	case LeadContactedColumn.LeadContactDts:
            		return this.LeadContactDts.CompareTo(rhs.LeadContactDts);
            		
            		                 
            	
            	
            	case LeadContactedColumn.LeadContactedPk:
            		return this.LeadContactedPk.CompareTo(rhs.LeadContactedPk);
            		
            		                 
            	
            	
            	case LeadContactedColumn.ThisEventDts:
            		return this.ThisEventDts.Value.CompareTo(rhs.ThisEventDts.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<LeadContactedKey> Members
		
		// member variable for the EntityId property
		private LeadContactedKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual LeadContactedKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new LeadContactedKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("LeadContacted")
					.Append("|").Append( this.LeadContactedPk.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{8}{7}- Leadid: {0}{7}- UserId: {1}{7}- LeadContactPhone: {2}{7}- LeadContactEmail: {3}{7}- LeadContactDts: {4}{7}- LeadContactedPk: {5}{7}- ThisEventDts: {6}{7}{9}", 
				this.Leadid,
				this.UserId,
				(this.LeadContactPhone == null) ? string.Empty : this.LeadContactPhone.ToString(),
				(this.LeadContactEmail == null) ? string.Empty : this.LeadContactEmail.ToString(),
				(this.LeadContactDts == null) ? string.Empty : this.LeadContactDts.ToString(),
				this.LeadContactedPk,
				(this.ThisEventDts == null) ? string.Empty : this.ThisEventDts.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'LeadContacted' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class LeadContactedEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// LeadContactedPK : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "LeadContacted"</remarks>
		public System.Int64 LeadContactedPk;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// LEADID : 
		/// </summary>
		public System.String Leadid = string.Empty;
		
		/// <summary>
		/// USER_ID : 
		/// </summary>
		public System.String UserId = string.Empty;
		
		/// <summary>
		/// LeadContactPhone : 
		/// </summary>
		public System.Boolean? LeadContactPhone = null;
		
		/// <summary>
		/// LeadContactEmail : 
		/// </summary>
		public System.Boolean? LeadContactEmail = null;
		
		/// <summary>
		/// LeadContactDts : 
		/// </summary>
		public System.String LeadContactDts = null;
		
		/// <summary>
		/// ThisEventDts : 
		/// </summary>
		public System.DateTime? ThisEventDts = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			LeadContactedEntityData _tmp = new LeadContactedEntityData();
						
			_tmp.LeadContactedPk = this.LeadContactedPk;
			
			_tmp.Leadid = this.Leadid;
			_tmp.UserId = this.UserId;
			_tmp.LeadContactPhone = this.LeadContactPhone;
			_tmp.LeadContactEmail = this.LeadContactEmail;
			_tmp.LeadContactDts = this.LeadContactDts;
			_tmp.ThisEventDts = this.ThisEventDts;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			LeadContactedEntityData _tmp = new LeadContactedEntityData();
						
			_tmp.LeadContactedPk = this.LeadContactedPk;
			
			_tmp.Leadid = this.Leadid;
			_tmp.UserId = this.UserId;
			_tmp.LeadContactPhone = this.LeadContactPhone;
			_tmp.LeadContactEmail = this.LeadContactEmail;
			_tmp.LeadContactDts = this.LeadContactDts;
			_tmp.ThisEventDts = this.ThisEventDts;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="LeadContactedColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(LeadContactedColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="LeadContactedColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(LeadContactedColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="LeadContactedColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(LeadContactedColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				LeadContactedEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new LeadContactedEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="LeadContactedColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(LeadContactedColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				LeadContactedEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new LeadContactedEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region LeadContactedEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="LeadContacted"/> object.
	/// </remarks>
	public class LeadContactedEventArgs : System.EventArgs
	{
		private LeadContactedColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the LeadContactedEventArgs class.
		///</summary>
		public LeadContactedEventArgs(LeadContactedColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the LeadContactedEventArgs class.
		///</summary>
		public LeadContactedEventArgs(LeadContactedColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The LeadContactedColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="LeadContactedColumn" />
		public LeadContactedColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all LeadContacted related events.
	///</summary>
	public delegate void LeadContactedEventHandler(object sender, LeadContactedEventArgs e);
	
	#region LeadContactedComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class LeadContactedComparer : System.Collections.Generic.IComparer<LeadContacted>
	{
		LeadContactedColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:LeadContactedComparer"/> class.
        /// </summary>
		public LeadContactedComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:LeadContactedComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public LeadContactedComparer(LeadContactedColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="LeadContacted"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="LeadContacted"/> to compare.</param>
        /// <param name="b">The second <c>LeadContacted</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(LeadContacted a, LeadContacted b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(LeadContacted entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(LeadContacted a, LeadContacted b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public LeadContactedColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region LeadContactedKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="LeadContacted"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class LeadContactedKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the LeadContactedKey class.
		/// </summary>
		public LeadContactedKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the LeadContactedKey class.
		/// </summary>
		public LeadContactedKey(LeadContactedBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.LeadContactedPk = entity.LeadContactedPk;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the LeadContactedKey class.
		/// </summary>
		public LeadContactedKey(System.Int64 _leadContactedPk)
		{
			#region Init Properties

			this.LeadContactedPk = _leadContactedPk;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private LeadContactedBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public LeadContactedBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the LeadContactedPk property
		private System.Int64 _leadContactedPk;
		
		/// <summary>
		/// Gets or sets the LeadContactedPk property.
		/// </summary>
		public System.Int64 LeadContactedPk
		{
			get { return _leadContactedPk; }
			set
			{
				if ( this.Entity != null )
					this.Entity.LeadContactedPk = value;
				
				_leadContactedPk = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				LeadContactedPk = ( values["LeadContactedPk"] != null ) ? (System.Int64) EntityUtil.ChangeType(values["LeadContactedPk"], typeof(System.Int64)) : (long)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("LeadContactedPk", LeadContactedPk);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("LeadContactedPk: {0}{1}",
								LeadContactedPk,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region LeadContactedColumn Enum
	
	/// <summary>
	/// Enumerate the LeadContacted columns.
	/// </summary>
	[Serializable]
	public enum LeadContactedColumn : int
	{
		/// <summary>
		/// Leadid : 
		/// </summary>
		[EnumTextValue("Leadid")]
		[ColumnEnum("LEADID", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 50)]
		Leadid = 1,
		/// <summary>
		/// UserId : 
		/// </summary>
		[EnumTextValue("User Id")]
		[ColumnEnum("USER_ID", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 50)]
		UserId = 2,
		/// <summary>
		/// LeadContactPhone : 
		/// </summary>
		[EnumTextValue("Lead Contact Phone")]
		[ColumnEnum("LeadContactPhone", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
		LeadContactPhone = 3,
		/// <summary>
		/// LeadContactEmail : 
		/// </summary>
		[EnumTextValue("Lead Contact Email")]
		[ColumnEnum("LeadContactEmail", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
		LeadContactEmail = 4,
		/// <summary>
		/// LeadContactDts : 
		/// </summary>
		[EnumTextValue("Lead Contact Dts")]
		[ColumnEnum("LeadContactDts", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		LeadContactDts = 5,
		/// <summary>
		/// LeadContactedPk : 
		/// </summary>
		[EnumTextValue("Lead Contacted Pk")]
		[ColumnEnum("LeadContactedPK", typeof(System.Int64), System.Data.DbType.Int64, true, true, false)]
		LeadContactedPk = 6,
		/// <summary>
		/// ThisEventDts : 
		/// </summary>
		[EnumTextValue("This Event Dts")]
		[ColumnEnum("ThisEventDts", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		ThisEventDts = 7
	}//End enum

	#endregion LeadContactedColumn Enum

} // end namespace
