using System;
using System.ComponentModel;

namespace SiH_SalesWorkflow.Entities
{
	/// <summary>
	///		The data structure representation of the 'ZohoCalls' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IZohoCalls 
	{
		/// <summary>			
		/// CallPK : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ZohoCalls"</remarks>
		System.Int64 CallPk { get; set; }
				
		
		
		/// <summary>
		/// ACCOUNTID : 
		/// </summary>
		System.String  Accountid  { get; set; }
		
		/// <summary>
		/// Billable : 
		/// </summary>
		System.String  Billable  { get; set; }
		
		/// <summary>
		/// Call Duration : 
		/// </summary>
		System.String  CallDuration  { get; set; }
		
		/// <summary>
		/// Call Duration (in minutes) : 
		/// </summary>
		System.Double?  SafeNameCallDurationInMinutes  { get; set; }
		
		/// <summary>
		/// Call Duration (in seconds) : 
		/// </summary>
		System.Double?  SafeNameCallDurationInSeconds  { get; set; }
		
		/// <summary>
		/// Call Owner : 
		/// </summary>
		System.String  CallOwner  { get; set; }
		
		/// <summary>
		/// Call Owner Id : 
		/// </summary>
		System.String  CallOwnerId  { get; set; }
		
		/// <summary>
		/// Call Purpose : 
		/// </summary>
		System.String  CallPurpose  { get; set; }
		
		/// <summary>
		/// Call Result : 
		/// </summary>
		System.String  CallResult  { get; set; }
		
		/// <summary>
		/// Call Start Time : 
		/// </summary>
		System.DateTime?  CallStartTime  { get; set; }
		
		/// <summary>
		/// Call Type : 
		/// </summary>
		System.String  CallType  { get; set; }
		
		/// <summary>
		/// ContactID : 
		/// </summary>
		System.String  ContactId  { get; set; }
		
		/// <summary>
		/// CreatedBy : 
		/// </summary>
		System.String  CreatedBy  { get; set; }
		
		/// <summary>
		/// Created Time : 
		/// </summary>
		System.DateTime?  CreatedTime  { get; set; }
		
		/// <summary>
		/// LEADID : 
		/// </summary>
		System.String  Leadid  { get; set; }
		
		/// <summary>
		/// Modified Time : 
		/// </summary>
		System.DateTime?  ModifiedTime  { get; set; }
		
		/// <summary>
		/// POTENTIALID : 
		/// </summary>
		System.String  Potentialid  { get; set; }
		
		/// <summary>
		/// RELATED To : 
		/// </summary>
		System.String  RelatedTo  { get; set; }
		
		/// <summary>
		/// SEMODULE : 
		/// </summary>
		System.String  Semodule  { get; set; }
		
		/// <summary>
		/// Subject : 
		/// </summary>
		System.String  Subject  { get; set; }
		
		/// <summary>
		/// TASKID : 
		/// </summary>
		System.String  Taskid  { get; set; }
		
		/// <summary>
		/// Who Id Id : 
		/// </summary>
		System.String  WhoIdId  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


